PATCH https://the-pretty-petals-backend.onrender.com/register/1
# {"content-type":"application/json"}
{"firstName": "kl","lastName": "gjh","email":"fgjgh","pass":"fgh","cart":[{"check":"ewfwefj"}],"wishlist":[{"check":"sddfoij"}]}